# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 22:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=140)),
                ('object_id', models.PositiveIntegerField()),
                ('mount', models.FloatField()),
                ('metodo', models.IntegerField(choices=[(1, 'Deposito'), (2, 'Trasferencia'), (3, 'Tarjeta'), (4, 'Oxxo')], default=1)),
                ('estado', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Verificado'), (3, 'Conflicto'), (4, 'Cancelado'), (5, 'Rembolsado')], default=1)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
