# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perfil_voz',
            new_name='Perfil_audio',
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='perfil_audio',
            options={'verbose_name_plural': 'Audios'},
        ),
        migrations.AlterModelOptions(
            name='perfil_carta',
            options={'verbose_name_plural': 'Cartas'},
        ),
        migrations.AlterModelOptions(
            name='perfil_video',
            options={'verbose_name_plural': 'Videos'},
        ),
    ]
