# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20161005_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil_audio',
            old_name='imagen',
            new_name='archivo',
        ),
        migrations.RenameField(
            model_name='perfil_video',
            old_name='imagen',
            new_name='archivo',
        ),
        migrations.RemoveField(
            model_name='perfil_carta',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='perfil_carta',
            name='imagen',
        ),
        migrations.AddField(
            model_name='perfil_carta',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=usuario.models.user_directoryfile_path, validators=[usuario.models.validar_carta]),
        ),
        migrations.AddField(
            model_name='perfil_carta',
            name='contenido',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='perfil_video',
            name='formato',
            field=models.IntegerField(blank=True, choices=[(1, 'Digital'), (2, 'USB'), (3, 'CD'), (4, 'DVD')], null=True),
        ),
    ]
