# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20161005_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_audio',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=usuario.models.user_directoryfile_path, validators=[usuario.models.validar_audio]),
        ),
    ]
