# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20161005_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_video',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=usuario.models.user_directoryfile_path, validators=[usuario.models.validar_video]),
        ),
    ]
