# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0005_auto_20161005_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='conteo_mensajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carta', models.IntegerField(default=0)),
                ('audio', models.IntegerField(default=0)),
                ('video', models.IntegerField(default=0)),
                ('carta_extra', models.IntegerField(default=0)),
                ('audio_extra', models.IntegerField(default=0)),
                ('video_extra', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='perfil_audio',
            name='terminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil_carta',
            name='terminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil_video',
            name='terminado',
            field=models.BooleanField(default=False),
        ),
    ]
