# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20161013_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_carta_archivo',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
