# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20161013_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_carta_archivo',
            name='carta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Perfil_carta'),
        ),
    ]
