# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_perfil_carta_archivo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_carta',
            name='tel1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='perfil_carta',
            name='tel2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
