# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_auto_20161016_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_carta_archivo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=usuario.models.user_directoryfile_path),
        ),
    ]
