# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 20:46
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_auto_20161022_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_carta',
            name='contacto',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='user', chained_model_field='nombre', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Contactos'),
        ),
    ]
