# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_auto_20161022_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_carta',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Contactos'),
        ),
    ]
