# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0015_auto_20161022_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil_carta',
            name='email',
        ),
        migrations.RemoveField(
            model_name='perfil_carta',
            name='tel1',
        ),
        migrations.RemoveField(
            model_name='perfil_carta',
            name='tel2',
        ),
    ]
