# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_auto_20161107_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil_audio_archivo',
            old_name='carta',
            new_name='audio',
        ),
    ]
