# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 22:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('descripcion', models.CharField(max_length=500)),
                ('costo', models.FloatField()),
                ('duracion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MembresiaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Activo'), (3, 'Cancelado')], default=1)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paquetes.Membresia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
